import { Inter } from 'next/font/google';
import Sketch from '@/lib/Sketch';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				{' '}
				<Sketch />
				<div style={{ position: 'relative', zIndex: 1 }}>{children}</div>
			</body>
		</html>
	);
}
